server:
  port: 8761

spring:
  application:
    name: discovery-server
  cloud:
    service-registry:
      auto-registration:
        enabled: false   # do not auto-register this app anywhere

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/  # ok even if not used
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info
